Fix links to Instructor Notes in lessons.html
swcarpentry/website-archive pull request #1244
Opened 2023-05-16 02:58 UTC by sarahmfrost

Fixing links to instructor notes for all lessons by changing "guide" to "instructor" ex:

https://swcarpentry.github.io/shell-novice/guide/ ->
https://swcarpentry.github.io/shell-novice/instructor/ 

This is part of my instructor checkout process.

2023-05-17 17:31 UTC, zkamvar requested changes
Thank you @sarahmfrost! The URL you point to goes to the instructor view, which does have a link to the instructor notes page. I've made suggestions to update the URL to point to the actual instructor notes page.

You can [apply these suggestions as one commit](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request) directly on GitHub by going to https://github.com/swcarpentry/website/pull/1244/files, selecting "Add suggestion to batch" for each one and then clicking on "Commit Suggestions" at the top.

2023-05-17 17:31 UTC, zkamvar commented on pages/lessons.html
> +    <td><a href="{{site.github_io_url}}/shell-novice/instructor/" target="_blank" class="icon-circle-with-plus" title="The Unix Shell Instructor Notes"></a></td>
```suggestion
    <td><a href="{{site.github_io_url}}/shell-novice/instructor/instructor-notes" target="_blank" class="icon-circle-with-plus" title="The Unix Shell Instructor Notes"></a></td>
```

2023-05-17 17:31 UTC, zkamvar commented on pages/lessons.html
> +    <td><a href="{{site.github_io_url}}/git-novice/instructor/" target="_blank" class="icon-circle-with-plus" title="Version Control with Git Instructor Notes"></a></td>
```suggestion
    <td><a href="{{site.github_io_url}}/git-novice/instructor/instructor-notes" target="_blank" class="icon-circle-with-plus" title="Version Control with Git Instructor Notes"></a></td>
```

2023-05-17 17:31 UTC, zkamvar commented on pages/lessons.html
> +    <td><a href="{{site.github_io_url}}/python-novice-inflammation/instructor/" target="_blank" class="icon-circle-with-plus" title="Programming with Python Instructor Notes"></a></td>
```suggestion
    <td><a href="{{site.github_io_url}}/python-novice-inflammation/instructor/instructor-notes" target="_blank" class="icon-circle-with-plus" title="Programming with Python Instructor Notes"></a></td>
```

2023-05-17 17:31 UTC, zkamvar commented on pages/lessons.html
> +      <td><a href="{{site.github_io_url}}/python-novice-gapminder/instructor/" target="_blank" class="icon-circle-with-plus" title="Plotting and Programming Instructor Notes"></a></td>
```suggestion
      <td><a href="{{site.github_io_url}}/python-novice-gapminder/instructor/instructor-notes" target="_blank" class="icon-circle-with-plus" title="Plotting and Programming Instructor Notes"></a></td>
```

2023-05-17 17:31 UTC, zkamvar commented on pages/lessons.html
> +    <td><a href="{{site.github_io_url}}/r-novice-inflammation/instructor/" target="_blank" class="icon-circle-with-plus" title="Programming with R Instructor Notes"></a></td>
```suggestion
    <td><a href="{{site.github_io_url}}/r-novice-inflammation/instructor/instructor-notes" target="_blank" class="icon-circle-with-plus" title="Programming with R Instructor Notes"></a></td>
```

2023-05-17 17:31 UTC, zkamvar commented on pages/lessons.html
> +    <td><a href="{{site.github_io_url}}/r-novice-gapminder/instructor/" target="_blank" class="icon-circle-with-plus" title="R for Reproducible Scientific Analysis Instructor Notes"></a></td>
```suggestion
    <td><a href="{{site.github_io_url}}/r-novice-gapminder/instructor/instructor-notes" target="_blank" class="icon-circle-with-plus" title="R for Reproducible Scientific Analysis Instructor Notes"></a></td>
```

2023-05-17 17:31 UTC, zkamvar commented on pages/lessons.html
> +    <td><a href="{{site.github_io_url}}/shell-novice-es/instructor/" target="_blank" class="icon-circle-with-plus" title="Notas para las personas instructoras de La Terminal de Unix"></a></td>
```suggestion
    <td><a href="{{site.github_io_url}}/shell-novice-es/instructor/instructor-notes" target="_blank" class="icon-circle-with-plus" title="Notas para las personas instructoras de La Terminal de Unix"></a></td>
```

2023-05-17 17:31 UTC, zkamvar commented on pages/lessons.html
> +    <td><a href="{{site.github_io_url}}/git-novice-es/instructor/" target="_blank" class="icon-circle-with-plus" title="Notas para las personas instructoras de Control de versiones con Git"></a></td>
```suggestion
    <td><a href="{{site.github_io_url}}/git-novice-es/instructor/instructor-notes" target="_blank" class="icon-circle-with-plus" title="Notas para las personas instructoras de Control de versiones con Git"></a></td>
```

2023-05-17 17:31 UTC, zkamvar commented on pages/lessons.html
> +      <td><a href="{{site.github_io_url}}/r-novice-gapminder-es/instructor/" target="_blank" class="icon-circle-with-plus" title="Notas para las personas instructoras de R para Análisis Científicos R
```suggestion
      <td><a href="{{site.github_io_url}}/r-novice-gapminder-es/instructor/instructor-notes" target="_blank" class="icon-circle-with-plus" title="Notas para las personas instructoras de R para Análisis Científicos Reproducibles"></a></td>
```

2023-05-17 17:31 UTC, zkamvar commented on pages/lessons.html
> +    <td><a href="{{site.github_io_url}}/make-novice/instructor/" target="_blank" class="icon-circle-with-plus" title="Automation and Make Instructor Notes"></a></td>
```suggestion
    <td><a href="{{site.github_io_url}}/make-novice/instructor/instructor-notes" target="_blank" class="icon-circle-with-plus" title="Automation and Make Instructor Notes"></a></td>
```

2023-05-17 17:31 UTC, zkamvar commented on pages/lessons.html
> +    <td><a href="{{site.github_io_url}}/matlab-novice-inflammation/instructor/" target="_blank" class="icon-circle-with-plus" title="Programming with MATLAB Instructor Notes"></a></td>
```suggestion
    <td><a href="{{site.github_io_url}}/matlab-novice-inflammation/instructor/instructor-notes" target="_blank" class="icon-circle-with-plus" title="Programming with MATLAB Instructor Notes"></a></td>
```

2023-05-17 17:31 UTC, zkamvar commented on pages/lessons.html
> +    <td><a href="{{site.github_io_url}}/sql-novice-survey/instructor/" target="_blank" class="icon-circle-with-plus" title="Using Databases and SQL Instructor Notes"></a></td>
```suggestion
    <td><a href="{{site.github_io_url}}/sql-novice-survey/instructor/" target="_blank" class="icon-circle-with-plus" title="Using Databases and SQL Instructor Notes"></a></td>
```
```suggestion
    <td><a href="{{site.github_io_url}}/sql-novice-survey/instructor/instructor-notes" target="_blank" class="icon-circle-with-plus" title="Using Databases and SQL Instructor Notes"></a></td>
```

2023-05-18 19:41 UTC, sarahmfrost commented
Thank you Zhian!

2023-05-18 21:32 UTC, zkamvar approved these changes

2023-05-18 21:47 UTC, merged