Added 'Assessment' page
swcarpentry/website-archive pull request #698
Opened 2017-04-20 13:04 UTC by kariljordan

@jduckles I added an 'Assessment' page with links to the public-survey-info repo. I don't know how to make sure this shows up under the 'About' dropdown. Can you make it go? :)

2017-04-22 18:18 UTC, rgaiacs requested changes
> I don't know how to make sure this shows up under the 'About' dropdown. Can you make it go? :)

If you follow my comments you should have this page under the "About" dropdown menu at the navigation bar.

2017-04-22 18:18 UTC, rgaiacs commented on pages/assessment.md
> +# Assessment
Need to replace this line with

~~~
---
layout: page-fullwidth
permalink: /assessment/
title: Assessment
redirect_from:
  - /pages/assessment.html
---
~~~

2017-04-22 18:18 UTC, rgaiacs commented on pages/assessment.md
> +# Surveys
This line should start with `##` instead of `#`.

2017-04-22 18:18 UTC, rgaiacs commented on pages/assessment.md
> +# Data
This line should start with `##` instead of `#`.

2017-04-22 18:18 UTC, rgaiacs commented on pages/assessment.md
> +- [Carpentry Long-Term Feedback Survey](https://www.surveymonkey.com/r/Preview/?sm=LksuekfCD3hzLW6lPkx9qhkRF5nDt8uGWpN7lq2Mx0Dqw1Zriv3qYFpu3XtR46ei)
You can remove this line since all the information it provide is in the previous paragraph.

2017-04-24 01:52 UTC, jduckles approved these changes
I've addressed these changes.

2017-04-24 01:52 UTC, merged

2017-04-24 16:12 UTC, kariljordan reviewed
Thank you @jduckles! Is there something I need to do to make it appear on the website? I still don't see it.

2017-04-26 02:51 UTC, jduckles commented
Just made the change to add it to the menu: https://github.com/swcarpentry/website/commit/cf531df6e607a85d9c7a0154dd298b4d2ded04a1